# Site settings
title: iQapla
email: info@iqapla.com
url: https://www.iqapla.com
description: "Soon the automatic trading world will go upside down."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: iQapla.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/iqapla

# Build settings
markdown: kramdown
permalink: pretty
